n = input('Digite algo:\n')
print('O tipo primitivo do que foi digitado é:', type(n))
print('Só tem epaços?', (n.isspace()))
print('Só tem números?', (n.isnumeric()))
print(n.isalpha())
print(n.isalnum())
print(n.isupper())
print(n.islower())
print(n.istitle())
